export const STRIPECONNECT_ONBOARDING_REQUEST =
  "STRIPECONNECT_ONBOARDING_REQUEST"
export const STRIPECONNECT_ONBOARDING_SUCCESS =
  "STRIPECONNECT_ONBOARDING_SUCCESS"
export const STRIPECONNECT_ONBOARDING_FAIL = "STRIPECONNECT_ONBOARDING_FAIL"


export const STRIPE_CLIENT_SECRET_REQUEST = "STRIPE_CLIENT_SECRET_REQUEST"
export const STRIPE_CLIENT_SECRET_SUCCESS = "STRIPE_CLIENT_SECRET_SUCCESS"
export const STRIPE_CLIENT_SECRET_FAIL = "STRIPE_CLIENT_SECRET_FAIL"
