export const STRIPECONNECT_CREATE_REQUEST = "STRIPECONNECT_CREATE_REQUEST"
export const STRIPECONNECT_CREATE_SUCCESS = "STRIPECONNECT_CREATE_SUCCESS"
export const STRIPECONNECT_CREATE_FAIL = "STRIPECONNECT_CREATE_FAIL"
export const STRIPECONNECT_CREATE_RESET = "STRIPECONNECT_CREATE_RESET"

export const STRIPECONNECT_ONBOARDING_REQUEST =
  "STRIPECONNECT_ONBOARDING_REQUEST"
export const STRIPECONNECT_ONBOARDING_SUCCESS =
  "STRIPECONNECT_ONBOARDING_SUCCESS"
export const STRIPECONNECT_ONBOARDING_FAIL = "STRIPECONNECT_ONBOARDING_FAIL"
