export const STRIPECONNECT_ONBOARDING_REQUEST =
  "STRIPECONNECT_ONBOARDING_REQUEST"
export const STRIPECONNECT_ONBOARDING_SUCCESS =
  "STRIPECONNECT_ONBOARDING_SUCCESS"
export const STRIPECONNECT_ONBOARDING_FAIL = "STRIPECONNECT_ONBOARDING_FAIL"
