export const TICKET_ADD_REQUEST = "TICKET_ADD_REQUEST"
export const TICKET_ADD_SUCCESS = "TICKET_ADD_SUCCESS"
export const TICKET_ADD_FAIL = "TICKET_ADD_FAIL"
export const TICKET_ADD_RESET = "TICKET_ADD_RESET"

export const TICKET_LIST_REQUEST = "TICKET_LIST_REQUEST"
export const TICKET_LIST_SUCCESS = "TICKET_LIST_SUCCESS"
export const TICKET_LIST_FAIL = "TICKET_LIST_FAIL"

export const TICKET_DETAILS_REQUEST = "TICKET_DETAILS_REQUEST"
export const TICKET_DETAILS_SUCCESS = "TICKET_DETAILS_SUCCESS"
export const TICKET_DETAILS_FAIL = "TICKET_DETAILS_FAIL"
