export const VENUE_ADD_REQUEST = "VENUE_ADD_REQUEST"
export const VENUE_ADD_SUCCESS = "VENUE_ADD_SUCCESS"
export const VENUE_ADD_FAIL = "VENUE_ADD_FAIL"
export const VENUE_ADD_RESET = "VENUE_ADD_RESET"

export const VENUE_UPDATE_REQUEST = "VENUE_UPDATE_REQUEST"
export const VENUE_UPDATE_SUCCESS = "VENUE_UPDATE_FAIL"
export const VENUE_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL"
export const VENUE_UPDATE_RESET = "VENUE_UPDATE_RESET"

export const VENUE_DELETE_REQUEST = "VENUE_DELETE_REQUEST"
export const VENUE_DELETE_SUCCESS = "VENUE_DELETE_SUCCESS"
export const VENUE_DELETE_FAIL = "VENUE_DELETE_FAIL"
export const VENUE_DELETE_RESET = "VENUE_DELETE_RESET"

export const VENUE_LIST_REQUEST = "VENUE_LIST_REQUEST"
export const VENUE_LIST_SUCCESS = "VENUE_LIST_SUCCESS"
export const VENUE_LIST_FAIL = "VENUE_LIST_FAIL"
