import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Arsalan Ali",
      email: "admin@wow-tickets.com",
      image: "/images/avatar/ali.png",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Adam",
      email: "user@wow-tickets.com",
      image: "/images/avatar/adam.png",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  events: [
    {
      name: "Worried About Henry Ibiza 2023",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim lorem non quam pulvinar posuere eu id dolor. Praesent ullamcorper magna tincidunt fermentum bibendum. Vivamus faucibus, ante sed molestie hendrerit, ipsum leo faucibus ante, in tincidunt lectus arcu a augue. Donec sollicitudin imperdiet ultricies. Nunc augue massa, accumsan vel lectus id, iaculis interdum est. Proin fringilla eros consectetur scelerisque ullamcorper. Nunc nec orci ut tellus volutpat lobortis vitae eget est. Phasellus nec pretium metus.",
      thumbnail: "/images/event-thumbnail-dummy.jpg",
      cover: "/images/event-banner-dummy.jpg",
      startDate: "22 May, 2023",
      endDate: "23 May, 2023",
      website: "www.example.com",
      restrictions: [],
      socialLinks: [],
      price: "35",
      user: null,
      category: null,
      venue: null,
      eventStatus: true,
    },
    {
      name: "Event 2",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim lorem non quam pulvinar posuere eu id dolor. Praesent ullamcorper magna tincidunt fermentum bibendum. Vivamus faucibus, ante sed molestie hendrerit, ipsum leo faucibus ante, in tincidunt lectus arcu a augue. Donec sollicitudin imperdiet ultricies. Nunc augue massa, accumsan vel lectus id, iaculis interdum est. Proin fringilla eros consectetur scelerisque ullamcorper. Nunc nec orci ut tellus volutpat lobortis vitae eget est. Phasellus nec pretium metus.",
      thumbnail: "/images/event-thumbnail-dummy.jpg",
      cover: "/images/event-banner-dummy.jpg",
      startDate: "22 May, 2023",
      endDate: "23 May, 2023",
      website: "www.example.com",
      restrictions: [],
      socialLinks: [],
      price: "35",
      user: null,
      category: null,
      venue: null,
      eventStatus: true,
    },
    {
      name: "Event 3",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim lorem non quam pulvinar posuere eu id dolor. Praesent ullamcorper magna tincidunt fermentum bibendum. Vivamus faucibus, ante sed molestie hendrerit, ipsum leo faucibus ante, in tincidunt lectus arcu a augue. Donec sollicitudin imperdiet ultricies. Nunc augue massa, accumsan vel lectus id, iaculis interdum est. Proin fringilla eros consectetur scelerisque ullamcorper. Nunc nec orci ut tellus volutpat lobortis vitae eget est. Phasellus nec pretium metus.",
      thumbnail: "/images/event-thumbnail-dummy.jpg",
      cover: "/images/event-banner-dummy.jpg",
      startDate: "22 May, 2023",
      endDate: "23 May, 2023",
      website: "www.example.com",
      restrictions: [],
      socialLinks: [],
      price: "35",
      user: null,
      category: null,
      venue: null,
      eventStatus: true,
    },
    {
      name: "Event 4",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim lorem non quam pulvinar posuere eu id dolor. Praesent ullamcorper magna tincidunt fermentum bibendum. Vivamus faucibus, ante sed molestie hendrerit, ipsum leo faucibus ante, in tincidunt lectus arcu a augue. Donec sollicitudin imperdiet ultricies. Nunc augue massa, accumsan vel lectus id, iaculis interdum est. Proin fringilla eros consectetur scelerisque ullamcorper. Nunc nec orci ut tellus volutpat lobortis vitae eget est. Phasellus nec pretium metus.",
      thumbnail: "/images/event-thumbnail-dummy.jpg",
      cover: "/images/event-banner-dummy.jpg",
      startDate: "22 May, 2023",
      endDate: "23 May, 2023",
      website: "www.example.com",
      restrictions: [],
      socialLinks: [],
      price: "35",
      user: null,
      category: null,
      venue: null,
      eventStatus: true,
    },
    {
      name: "Event 5",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim lorem non quam pulvinar posuere eu id dolor. Praesent ullamcorper magna tincidunt fermentum bibendum. Vivamus faucibus, ante sed molestie hendrerit, ipsum leo faucibus ante, in tincidunt lectus arcu a augue. Donec sollicitudin imperdiet ultricies. Nunc augue massa, accumsan vel lectus id, iaculis interdum est. Proin fringilla eros consectetur scelerisque ullamcorper. Nunc nec orci ut tellus volutpat lobortis vitae eget est. Phasellus nec pretium metus.",
      thumbnail: "/images/event-thumbnail-dummy.jpg",
      cover: "/images/event-banner-dummy.jpg",
      startDate: "22 May, 2023",
      endDate: "23 May, 2023",
      website: "www.example.com",
      restrictions: [],
      socialLinks: [],
      price: "35",
      user: null,
      category: null,
      venue: null,
      eventStatus: true,
    },
  ],
  categories: [
    {
      name: "Club Night",
      description: "lorem ipsum is a dummy text use as a placeholder.",
      image: "http://via.placeholder.com/150x150",
    },
    {
      name: "Comedy",
      description: "lorem ipsum is a dummy text use as a placeholder.",
      image: "http://via.placeholder.com/150x150",
    },
    {
      name: "Conferences And Talks",
      description: "lorem ipsum is a dummy text use as a placeholder.",
      image: "http://via.placeholder.com/150x150",
    },
    {
      name: "Dance Performances And Classes",
      description: "lorem ipsum is a dummy text use as a placeholder.",
      image: "http://via.placeholder.com/150x150",
    },
  ],
  venues: [
    {
      name: "ABC 1",
      image: "http://via.placeholder.com/150x150",
      streetAddress: "196 Poolstock Ln",
      city: "Wigan",
      state: "Greater Manchester",
      postalCode: "WN3 5HW",
      country: "United Kingdom",
      lang: "",
      long: "",
    },
    {
      name: "ABC 2",
      image: "http://via.placeholder.com/150x150",
      streetAddress: "Cowley Rd",
      city: "Uxbridge",
      state: "Greater London",
      postalCode: "UB8 2AQ",
      country: "United Kingdom",
      lang: "",
      long: "",
    },
  ],
}

export default data
